export enum CostCenter {
  CENTRAL = 'CENTRAL',
  OPERACIONES = 'OPERACIONES',
  CONTENIDO = 'CONTENIDO',
  COMERCIAL = 'COMERCIAL',
  ADMINISTRACION = 'ADMINISTRACION',
  D360 = 'D360',
  CTA_CTE = 'CTA_CTE',
  VARIOS_FILES = 'VARIOS_FILES',
  OTHER = 'OTHER',
}
