export enum PaymentMethod {
  CASH = 'CASH',
  CASH_RENDITION = 'CASH_RENDITION',
  TC_AMEX = 'TC_AMEX',
  TC_GALICIA = 'TC_GALICIA',
  TC_PATAGONIA = 'TC_PATAGONIA',
  TC_SANTANDER = 'TC_SANTANDER',
  TC_CIUDAD = 'TC_CIUDAD',
}
